# Cleaning

## 파일 읽기

```{r}
library(tidyverse)
list.files(path = "data") -> file_v
file_v
```


```{r}
library(readxl)
paste0("data/", file_v) %>% read_excel(sheet = "Raw") -> df
head(df)
```

## 파일 정리
Q7 계열 열은 조건별로 각각 다른 열에 값이 있지만, 모두 같은 열에 값을 모아야 한다. 

- Q7으로 시작하는 열에서 `NA`를 모두 0으로 바꾼다.  
- 각 Q7의 열을 모두 더한다.  
  - 값을 모은 것이므로 나누기 하지 않는다. 

```{r}
df %>% 
  mutate_at(vars(starts_with("Q7")), 
            ~replace(., is.na(.), 0)) %>% 
  mutate(
    intensity1 = Q7_1_1 + Q7_2_1 + Q7_3_1 + Q7_4_1 + Q7_5_1,
    intensity2 = Q7_1_2 + Q7_2_2 + Q7_3_2 + Q7_4_2 + Q7_5_2,
    intensity3 = Q7_1_3 + Q7_2_3 + Q7_3_3 + Q7_4_3 + Q7_5_3,
    intensity4 = Q7_1_4 + Q7_2_4 + Q7_3_4 + Q7_4_4 + Q7_5_4,
    intensity5 = Q7_1_5 + Q7_2_5 + Q7_3_5 + Q7_4_5 + Q7_5_5
  ) -> df

df %>% 
  select(starts_with("intensity")) %>% 
  head()
```
Open 시트에 기록된 문자열도 하나의 열에 모은다. 

`tidyr::unite()` 함수는 여러 열을 하나의 열로 결합하는 데 사용. 이 함수는 NA 값을 고려하여 열을 결합할 때 매우 유용. 기본적으로 unite는 NA 값을 제외하고 열을 결합.


```{r}
library(readxl)
paste0("data/", file_v) %>% read_excel(sheet = "Open") -> df_open
head(df_open) 

df_open %>% 
  unite(exp1, Q7_1_1_1, Q7_1_2_1, Q7_1_3_1, Q7_1_4_1, Q7_1_5_1, sep = "", na.rm = T) %>% 
  unite(exp2, Q7_1_1_2, Q7_1_2_2, Q7_1_3_2, Q7_1_4_2, Q7_1_5_2, sep = "", na.rm = T) %>% 
  unite(exp3, Q7_1_1_3, Q7_1_2_3, Q7_1_3_3, Q7_1_4_3, Q7_1_5_3, sep = "", na.rm = T) %>% 
  unite(exp_detail, Q7_2_1_1, Q7_2_2_1, Q7_2_3_1, Q7_2_4_1, Q7_2_5_1, sep = "", na.rm = T) %>% 
  select(starts_with("exp")) %>% 
  head()  
```







